import type { Metadata } from "next";
import { Instrument_Serif, Hind_Madurai } from "next/font/google";
import "@/app/styles/globals.css";
import "@/app/styles/button.css";
import Header from "./components/ui/header";
import Footer from "./components/ui/footer";

import Provider from "./utils/provider";

export const bodyFont = Hind_Madurai({
    subsets: ["latin"],
    variable: "--font-body",
    weight: ["300", "400", "500", "600", "700"],
    fallback: ["arial"],
});
export const headinfFont = Instrument_Serif({
    subsets: ["latin"],
    variable: "--font-heading",
    style: "normal",
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${bodyFont.className} antialiased`}>
                <Provider>
                    <Header />
                    {children}
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
