import type { Metadata } from "next";

import "@/app/styles/globals.css";

import Header from "./components/ui/header";
import Footer from "./components/ui/footer";

import Provider from "./lib/provider";
import { Hind_Madurai_Font, Instrument_Serif_Font } from "./lib/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${Hind_Madurai_Font.className} antialiased`}>
                <Provider>
                    <Header />
                    {children}
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
